spring:
  data:
    mongodb:
      username: hamidali
      password: hamidali
      database: customer
      port: 27017
      host: localhost
      authentication-database: admin
server:
  port: 8090