spring:
  data:
    mongodb:
      username: hamidali
      password: hamidali
      database: notification
      port: 27017
      host: localhost
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notificationGroup  # Single group ID
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'dev.hamidz.ecommerce.kafka.*'  # More specific than '*'
        spring.json.type.mapping: >-
          orderConfirmation:dev.hamidz.ecommerce.kafka.order.OrderConfirmation,
          paymentConfirmation:dev.hamidz.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: hamidali
    password: hamidali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection timeout: 5000
        timeout: 3000
        write-timeout: 5000
server:
  port: 8040