spring:
  data:
    mongodb:
      username: hamidali
      password: hamidali
      database: customer
      port: 27017
      host: localhost
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:dev.hamidz.ecommerce.kafka.OrderConfirmation, paymentConfirmation:dev.hamidz.ecommerce.notification.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: hamidali
    password: hamidali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000
server:
  port: 8040